### ISSUE TITLE
remove some rules

### ISSUE THREAD

**Issue by harleyyyyymayes** [vktec-irc/vktec-irc-conduct#11]
Remove the caps rule. Get rid of +NS on #chat

**Comment by shymega** [comment]
Rejected. We prohibit caps for a reason. 
+S is there because people abused colors, so that is banned.
+N is there because people were changing their nicks frequently.

**Comment by shymega** [comment]
+N has been removed. Instead Mjon will (when ready) monitor for flood nick changes, and kick/warn when needed.

**Comment by shymega** [comment]
In future, give /reasons/ for your points. This comes across as a demanding, and gives no M.O for removing the rules. Likewise with the PR as well.
Just for future reference.
