### ISSUE TITLE
Merge rewritten CoC into master

### ISSUE THREAD

**Issue by shymega** [vktec-irc/vktec-irc-conduct#12]
I have taken the liberty of rewriting the Code of Conduct into less
'harsh' manner, and made it more advisory, as to not scare off new
users, and to make the network a less tense place.

I think it's time to merge the `rewrite` branch into `master`.

@zleap, @vktec - thoughts? And anyone else watching this repo for that
matter.

**Comment by shymega** [comment]
@zleap, @vktec - We need to merge this into master.

Any thoughts?

I may have to merge this into `master`, if there's no reply in a
couple of days, as it is a high priority we get the new conduct in
place.

**Comment by vktec** [comment]
I've just scanned through the new version. Looks good, I suggest we proceed to a PR.

**Comment by shymega** [comment]
This has been merged. Closing.
