### ISSUE TITLE
Choose license for Code of Conduct (IRC)

### ISSUE THREAD

**Issue by shymega** [vktec-irc/vktec-irc-conduct#14]
We should choose a license for the IRC Code of Conduct.

Perhaps CC-BY-SA would be a good choice? We use that for Tech Jam
stuff as well.

This repo is *currently* `All Rights Reserved` to the creator, @vktec.

We need to ask *all* previous contributors and get their written
consent to assign an license.

Thoughts?

**Comment by vktec** [comment]
Yeah, either CC-BY-SA or CC-BY-NC-SA would be my recommendation.

**Comment by shymega** [comment]
Samadi van Koten <notifications@github.com> writes:

> Yeah, either CC-BY-SA or CC-BY-NC-SA would be my recommendation.

No, CC-BY-NC-SA is a non-free license.

Please see on gnu.org  - rms wrote a piece on the problems with
CC-BY-NC-SA - for information on the non-freeness of CC-BY-NC-SA.

I personally don't feel the Tech Jam needs to limit commercial use.

I'd recommend CC-BY-SA, as it respects the essential freedoms, and
does not restrict usage.

-- 
Best regards,
Dom Rodriguez

**Comment by shymega** [comment]
Dom Rodriguez <notifications@github.com> writes:

> Samadi van Koten <notifications@github.com> writes:
>
>> Yeah, either CC-BY-SA or CC-BY-NC-SA would be my recommendation.
>
> No, CC-BY-NC-SA is a non-free license.
>
> Please see on gnu.org  - rms wrote a piece on the problems with
> CC-BY-NC-SA - for information on the non-freeness of CC-BY-NC-SA.
>
> I personally don't feel the Tech Jam needs to limit commercial use.
>
> I'd recommend CC-BY-SA, as it respects the essential freedoms, and
> does not restrict usage.
>
> -- 
> Best regards,
> Dom Rodriguez

For clarity, the link I was talking about is below:

https://stallman.org/articles/online-education.html

-- 
Best regards,
Dom Rodriguez

**Comment by vktec** [comment]
Good point, let's go with CC-BY-SA, unless there are any objections

**Comment by shymega** [comment]
None from me here.

**Comment by shymega** [comment]
As there has been 21 days for this to be objected to, we can now apply the CC BY-SA license.
I'll add it to my TODO list to do later. Once the coursework is all done.
