### ISSUE TITLE
Add Click CEOP button to the vKTec IRC website

### ISSUE THREAD

**Issue by zleap** [vktec-irc/vktec-irc-conduct#9]
I have added a click CEOP button to the Torbay Tech Jam website (downloaded the image from a school site and uploaded).  This links to https://www.ceop.police.uk/safety-centre/

This allows people (esp under 18s) to report serious issues either on vKTec IRC _or_ elsewhere if a child is worried or being targeted elsewhere.  Quite a lot of places also do this plus schools etc,  so we would be following what seems to be common practice.

**Comment by vktec** [comment]
**Note: Although this isn't _really_ the right place for this suggestion, as the vKTec IRC website repo would be better, I've not created that repo yet, so this will do.**

While this is an interesting suggestion, I'm not sure about whether it will actually be useful, as most people will be able to search the internet to find where to report things, or will speak to us directly, over IRC.

Any other thoughts?

**Comment by vktec** [comment]
What do you think about this @shymega?

**Comment by shymega** [comment]
Samadi van Koten <notifications@github.com> writes:

> What do you think about this @shymega?
>
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/vktec-irc/vktec-irc-conduct/issues/9#issuecomment-232289113

I think it's probably a good idea, but we should make sure the 'button'
can be used with NoScript, or other privacy enhancing
applications. Perhaps just a image with an link element?

-- 
Regards,
--
Dom Rodriguez

GnuPG Fingerprint: EB0D 45E6 D0DC 1BA1 A2B5 FC24 72DC F123 1E54 BD43
Email: shymega@shymega.org.uk
Website: https://www.shymega.org.uk

**Comment by vktec** [comment]
Yeah, good point.

**Comment by zleap** [comment]
I agree, the button on the tech jam home page is just this,  I downloaded the image and it links directly to the ceop webpage.   I, like you.  don't want stuff tracking me or loading in other sites there is no need for it.

**Comment by shymega** [comment]
Is this _really_ still necessary, considering the TTJ has moved to Freenode? Perhaps this would be better on the TTJ's website?

**Comment by vktec** [comment]
I agree. Not to mention that the vKTec IRC website has been down for several months.

**Comment by shymega** [comment]
So that in mind, perhaps we could close this issue, and mark it as WONTFIX?
